# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Jason Guan
tagline:          'Design and Data Guy'
description:      "World\'s OK-ist Designer. World's even OK-er Data Guy."
url:              http://jy-guan.github.io
baseurl:          ''

author:
  name:           'Jason Guan'

paginate:         5
paginate_path:       "page:num"

# Custom vars
version:          0.0.1
github_username:  jy-guan
