# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://jy-guan.github.io
baseurl:          ''

author:
  name:           'Jason Guan'

paginate:         5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0
